#!/bin/sh


# $1 : name of container ( name in lxc-start with -n)
# $2 : net
# $3 : network flags, up or down
# $4 : network type, for example, veth
# $5 : value of lxc.network.veth.pair

ovs-vsctl --may-exist add-br $Bridge
if [ "$GatewayHost" != "NULL" ]; then
  ovs-vsctl --may-exist add-port $Bridge vxlan-$UserID-$GatewayHost -- set interface vxlan-$UserID-$GatewayHost type=vxlan options:remote_ip=$GatewayHost options:key=$UserID
fi
ovs-vsctl --may-exist add-port $Bridge $5
