"""empty message

Revision ID: 37dcfdb2604
Revises: None
Create Date: 2018-04-22 11:58:48.307690

"""

# revision identifiers, used by Alembic.
revision = '37dcfdb2604'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(timezone=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('imagename', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasPrivate', sa.Boolean(), nullable=True),
    sa.Column('hasPublic', sa.Boolean(), nullable=True),
    sa.Column('ownername', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v_cluster',
    sa.Column('clusterid', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('clustername', sa.String(length=50), nullable=True),
    sa.Column('ownername', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('nextcid', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('proxy_server_ip', sa.String(length=20), nullable=True),
    sa.Column('proxy_public_ip', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('clusterid')
    )
    op.create_table('v_node',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('laststopcpuval', sa.Float(), nullable=True),
    sa.Column('laststopruntime', sa.Integer(), nullable=True),
    sa.Column('billing', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('billing_history',
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('vclusterid', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('mem', sa.Float(), nullable=True),
    sa.Column('disk', sa.Float(), nullable=True),
    sa.Column('port', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vclusterid'], ['v_cluster.clusterid'], ),
    sa.PrimaryKeyConstraint('node_name')
    )
    op.create_table('container',
    sa.Column('containername', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('host', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('lastsave', sa.DateTime(), nullable=True),
    sa.Column('setting_cpu', sa.Integer(), nullable=True),
    sa.Column('setting_mem', sa.Integer(), nullable=True),
    sa.Column('setting_disk', sa.Integer(), nullable=True),
    sa.Column('vclusterid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vclusterid'], ['v_cluster.clusterid'], ),
    sa.PrimaryKeyConstraint('containername')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vnode', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('runningtime', sa.Integer(), nullable=True),
    sa.Column('cputime', sa.Float(), nullable=True),
    sa.Column('billing', sa.Integer(), nullable=True),
    sa.Column('actionTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vnode'], ['v_node.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('node_ip', sa.String(length=20), nullable=True),
    sa.Column('node_port', sa.Integer(), nullable=True),
    sa.Column('host_port', sa.Integer(), nullable=True),
    sa.Column('vclusterid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vclusterid'], ['v_cluster.clusterid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('port_mapping')
    op.drop_table('history')
    op.drop_table('container')
    op.drop_table('billing_history')
    op.drop_table('v_node')
    op.drop_table('v_cluster')
    op.drop_table('image')
    op.drop_table('apply_msg')
    ### end Alembic commands ###
